import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "sonner";
import StoreProvider from "./_components/StoreProvider";
import Footer from "./_components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Courses App",
    template: " Courses App | %s ",
  },
  description: "Generated by create next app",
  keywords: ["next.js", "react", "course app"],
  authors: [
    {
      name: "Eslam",
      url: "https://yourwebsite.com",
    },
  ],
  creator: "Eslam",
  publisher: "Eslam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
